// shared list of municipalities used for the 30‑km fallback and the manual
// "show all" button. Kept in a separate module so both the API route and the
// UI can import it without duplicating the huge array.

export const STATIC_TOWNS: string[] = [
  'Babice',
  'Barchov (u HK)',
  'Barchov (u Pardubic)',
  'Barchůvek',
  'Bašnice',
  'Benátky (u HK)',
  'Bezděkov',
  'Bílé Poličany',
  'Bílsko u Hořic',
  'Blata',
  'Blato',
  'Boháňka',
  'Boharyně',
  'Borek',
  'Brada-Rybníček',
  'Březina',
  'Březovice',
  'Bříšťany',
  'Brozany',
  'Bukovka',
  'Bukvice',
  'Bylany',
  'Čankovice',
  'Čejkovice',
  'Čenice',
  'Čeperka',
  'Čepí',
  'Cerekvice nad Bystřicí',
  'Černá u Bohdanče',
  'Černá za Bory',
  'Čertovina',
  'Červený Kostelec',
  'Česká Skalice',
  'Češov',
  'Chloumek',
  'Chlum (u Všestar)',
  'Chlumětín',
  'Chodovice',
  'Chomutice',
  'Dašice',
  'Dědek',
  'Dědová',
  'Dílce',
  'Dlouhé Dvory',
  'Dobeš',
  'Dobrá Voda u Hořic',
  'Dobřenice',
  'Dohalice',
  'Dolany',
  'Dolní Babákov',
  'Dolní Bousov',
  'Dolní Černůtky (u Jeřic)',
  'Dolní Holetín',
  'Dolní Nová Ves',
  'Dolní Přím',
  'Dolní Radechová',
  'Dolní Roveň',
  'Domoslavice',
  'Dřenice',
  'Dříteč',
  'Drozdice',
  'Dub (u Mžan)',
  'Dubany',
  'Filipov',
  'Františky',
  'Habřinka',
  'Hamry',
  'Herálec',
  'Hlásná Lhota',
  'Hlinsko',
  'Hněvčeves',
  'Holetín',
  'Holín',
  'Holovousy',
  'Homyle',
  'Hořice',
  'Horní Babákov',
  'Horní Dohalice',
  'Horní Holetín',
  'Horní Nová Ves',
  'Horní Přím',
  'Hrádek (u Nechanic)',
  'Hradíšťko',
  'Hřídelec',
  'Hrobice',
  'Hrochův Týnec',
  'Hronov',
  'Hubálov',
  'Hubojedy',
  'Hvozdnice (u HK)',
  'Jaroměř',
  'Jeníkov',
  'Jeníkovice',
  'Jeřice',
  'Jezbořice',
  'Jičín',
  'Jinolice',
  'Jivany',
  'Kameničky',
  'Kbelnice',
  'Kladno (Pardubický kraj)',
  'Klešice',
  'Kněžnice',
  'Kobylice',
  'Komárov (u Nechanic)',
  'Konecchlumí',
  'Košinov',
  'Kostěnice',
  'Kovač',
  'Kozojedy',
  'Králíky (u Nového Bydžova)',
  'Kratonohy',
  'Křičeň',
  'Krouna',
  'Kunčice',
  'Kunětice',
  'Lány (u Chrudimi)',
  'Lány (u Lázní Bělohrad)',
  'Lány na Důlku',
  'Lány u Dašic',
  'Lázně Bělohrad',
  'Lázně Bohdaneč',
  'Lhota pod Libčany',
  'Libčany',
  'Liběšice',
  'Libošovice',
  'Libuň',
  'Lískovice',
  'Lodín',
  'Lubno (u Nechanic)',
  'Lukavec u Hořic',
  'Lužany',
  'Medkovy Kopce',
  'Medlešice',
  'Mělice',
  'Měník',
  'Michnovka',
  'Mikulovice',
  'Miletín',
  'Milovice u Hořic',
  'Mladějov',
  'Mlázovice',
  'Mnětice',
  'Mokrovousy',
  'Morašice',
  'Mrákotín',
  'Mžany',
  'Náchod',
  'Náchodsko',
  'Nákle',
  'Nechanice',
  'Němčice',
  'Nemošice',
  'Nemyčeves',
  'Neratov',
  'Nerošov',
  'Nevratice',
  'Nová Paka',
  'Nové Město nad Metují',
  'Nové Smrkovice',
  'Novinsko',
  'Nový Bydžov',
  'Obědovice',
  'Obora',
  'Opatovice nad Labem',
  'Opočínek',
  'Osice',
  'Osičky',
  'Ostřešany',
  'Ostroměř',
  'Ostrov (u Třebnouševsi)',
  'Ostružno',
  'Otradov',
  'Pardubice',
  'Plch',
  'Podhorní Újezd',
  'Podhorní Újezd a Vojice',
  'Podhradí',
  'Podoliby',
  'Pohránov',
  'Polizy',
  'Popkovice',
  'Popovice',
  'Prasek',
  'Přelouč',
  'Přibyslav, okres Náchod',
  'Příkrakov',
  'Probluz',
  'Prosetín',
  'Provodov-Šonov',
  'Pustá Kamenice',
  'Ráby',
  'Radíkovice',
  'Radostov',
  'Rašín',
  'Rohovládova Bělá',
  'Rohoznice (u Miletína)',
  'Rohoznice u Pardubic',
  'Rokytno',
  'Rosnice (u Všestar)',
  'Roudnice',
  'Roveň',
  'Rozběřice',
  'Rozhovice',
  'Rváčov',
  'Sadová (u HK)',
  'Samšina',
  'Šaplava',
  'Šárovcova Lhota',
  'Sběř',
  'Semtín',
  'Sezemice',
  'Skála (u Boháňky)',
  'Skupice',
  'Slatiny',
  'Sobčice',
  'Sobětuš',
  'Sobotka',
  'Sovětice',
  'Spojil',
  'Srch',
  'Srní',
  'Srnojedy',
  'Staňkova Lhota',
  'Staré Čívice',
  'Staré Hradiště',
  'Staré Hrady',
  'Staré Jesenčany',
  'Staré Místo',
  'Staré Nechanice',
  'Staré Smrkovice',
  'Staré Ždánice',
  'Staročernsko',
  'Starý Mateřov',
  'Stéblová',
  'Stěžírky',
  'Stolany',
  'Stračov',
  'Střezetice',
  'Střítěž',
  'Studnice',
  'Suchá (u Nechanic)',
  'Sukorady',
  'Svatojánský Újezd',
  'Svratka',
  'Svratouch',
  'Syrovátka',
  'Těchlovice',
  'Trávník',
  'Třebnouševes',
  'Třebosice',
  'Třebovětice',
  'Třesovice',
  'Trhová Kamenice',
  'Třibřichy',
  'Třtěnice',
  'Tůně (Nechanice)',
  'Tuněchody',
  'Tuř',
  'Újezd pod Troskami',
  'Úlibice',
  'Velešice',
  'Veliš',
  'Velké Poříčí',
  'Velký Vřešťov',
  'Veselí',
  'Vidochov',
  'Vinice',
  'Vítanov',
  'Vitiněves',
  'Vlhošť',
  'Vojice',
  'Vojtěchov',
  'Vokšice',
  'Volanice',
  'Voleč',
  'Vortová',
  'Vrbice',
  'Všestary',
  'Vyhnánov',
  'Vyšehněvice',
  'Vysoká nad Labem',
  'Vysoké Veselí',
  'Vysokov',
  'Zábrodí',
  'Zámostí-Blata',
  'Zdechovice (u HK)',
  'Zdobín',
  'Želí',
  'Žeretice',
  'Zminný',
  'Zvíkov',
].sort((a, b) => a.localeCompare(b, 'cs'));
